# Generated by Django 2.2.7 on 2019-11-21 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('host_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('host_phone', models.IntegerField()),
                ('host_desc', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.TextField(max_length=100)),
                ('current_meeting_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_phone', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2019, 11, 21, 8, 40, 54, 666803))),
                ('time_in', models.TimeField(default=datetime.datetime(2019, 11, 21, 8, 40, 54, 666803))),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
