# Generated by Django 2.2.7 on 2019-11-21 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191121_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 13, 21, 39, 755404)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 11, 21, 13, 21, 39, 755404)),
        ),
    ]
