# Generated by Django 2.2.7 on 2019-11-21 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191121_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_image',
            field=models.ImageField(upload_to='img/doctors'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 14, 16, 32, 850274)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 11, 21, 14, 16, 32, 850274)),
        ),
    ]
