# Generated by Django 2.2.7 on 2019-11-21 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191121_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='available',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 15, 21, 33, 566408)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 11, 21, 15, 21, 33, 566408)),
        ),
    ]
