# Generated by Django 2.2.7 on 2019-11-21 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191121_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 21, 20, 13, 150281)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 11, 21, 21, 20, 13, 150281)),
        ),
    ]
