# Generated by Django 2.2.7 on 2019-11-21 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191121_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 0, 18, 34, 480964)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 11, 22, 0, 18, 34, 480964)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitor_phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
